version: "3.7"
services:
    jhipster6:
        image: jhipster/jhipster:v6.10.5
        volumes:
        #to-do parameterize ~/projects/git.  In the meanwhile you'll need to tweak ~/projects/git to a folder location on your computer that you use for development.
            - ~/projects/git:/home/jhipster/app
            - ~/.m2:/home/jhipster/.m2
        ports:
            - "18080:8080"
            - "19000:9000"
            - "13001:3001"
        working_dir: /home/jhipster/app

    jhipster7:
        image: jhipster/jhipster:v7.9.3
        volumes:
         #to-do parameterize ~/projects/git.  In the meanwhile you'll need to tweak ~/projects/git to a folder location on your computer that you use for development.
            - ~/projects/git:/home/jhipster/app
            - ~/.m2:/home/jhipster/.m2
        ports:
            - "28080:8080"
            - "29000:9000"
            - "23001:3001"
        working_dir: /home/jhipster/app
    jhipsterDotNetCore:
        image: jhipster-generator-dotnetcore:latest
        volumes:
        #to-do parameterize ~/projects/git.  In the meanwhile you'll need to tweak ~/projects/git to a folder location on your computer that you use for development.
            - ~/projects/git:/home/jhipster/app
         #   - ~/.m2:/home/jhipster/.m2
        ports:
            - "48080:8080"
            - "49000:9000"
            - "43001:3001"
        working_dir: /home/jhipster/app        
    
    jdl-studio:
        image: jhipster/jdl-studio:latest
        ports:
            - "38080:80"